name: tuxvsdragon
base: core22
version: '1.0'
license: GPL-2.0-only
summary: Slay the Red Dragon Tux!
description: |
  You have to kill the dragon. It takes 24 snowball hits to kill the dragon. If Tux gets hit just once you have to start all over again! Snowballs will randomly spawn in one of the four grassy patches, Tux can only carry one at a time and cant throw a snowball unless he is standing still. Good luck!

  W,A,S,D / Arrow Keys = Move
  Space Bar = Throw Snowball

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  tuxvsdragon:
    extensions: [gnome]
    command: tuxvsdragon
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  tuxvsdragon:
    source: https://github.com/mrbid/tuxvsdragon
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2